// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Master.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class MasterHandler : virtual public MasterIf {
 public:
  MasterHandler() {
    // Your initialization goes here
  }

  int32_t AssignId() {
    // Your implementation goes here
    printf("AssignId\n");
  }

  void AssignTask(TaskResponse& _return) {
    // Your implementation goes here
    printf("AssignTask\n");
  }

  void CommitTask(const TaskResult& result) {
    // Your implementation goes here
    printf("CommitTask\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<MasterHandler> handler(new MasterHandler());
  ::std::shared_ptr<TProcessor> processor(new MasterProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

